// <auto-generated />
using System;
using Hummingbird.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hummingbird.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hummingbird.API.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasConversion(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A = Fix-rate per employee, B = Workday-rate",
                            Key = "ServiceChargeVersion",
                            UpdatedAt = new DateTime(2026, 4, 6, 13, 14, 15, 157, DateTimeKind.Utc).AddTicks(4210),
                            Value = "A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Company / property name",
                            Key = "CompanyName",
                            UpdatedAt = new DateTime(2026, 4, 6, 13, 14, 15, 157, DateTimeKind.Utc).AddTicks(4210),
                            Value = "My Hotel"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Whether initial setup has been completed",
                            Key = "Onboarded",
                            UpdatedAt = new DateTime(2026, 4, 6, 13, 14, 15, 157, DateTimeKind.Utc).AddTicks(4210),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("Hummingbird.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone")
                        .HasConversion(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Hummingbird.API.Models.PayrollRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasConversion(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

                    b.Property<decimal>("Deductions")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("MissingDays")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PenaltyDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceChargeBonus")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ServiceChargeInput")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ServiceChargeVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalScheduledDays")
                        .HasColumnType("integer");

                    b.Property<int>("WorkDays")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("PayrollRecords");
                });

            modelBuilder.Entity("Hummingbird.API.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ClockInTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ClockOutTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("DefaultSalary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ServiceChargePercentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClockInTime = new TimeSpan(0, 8, 0, 0, 0),
                            ClockOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            DefaultSalary = 15000m,
                            Name = "Food and Beverage",
                            ServiceChargePercentage = 25m,
                            ShiftType = "Morning",
                            TotalHours = 9m
                        },
                        new
                        {
                            Id = 2,
                            ClockInTime = new TimeSpan(0, 7, 0, 0, 0),
                            ClockOutTime = new TimeSpan(0, 16, 0, 0, 0),
                            DefaultSalary = 12000m,
                            Name = "Cleaner",
                            ServiceChargePercentage = 20m,
                            ShiftType = "Morning",
                            TotalHours = 9m
                        },
                        new
                        {
                            Id = 3,
                            ClockInTime = new TimeSpan(0, 8, 0, 0, 0),
                            ClockOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            DefaultSalary = 18000m,
                            Name = "Receptionist",
                            ServiceChargePercentage = 30m,
                            ShiftType = "Morning",
                            TotalHours = 9m
                        },
                        new
                        {
                            Id = 4,
                            ClockInTime = new TimeSpan(0, 8, 0, 0, 0),
                            ClockOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            DefaultSalary = 35000m,
                            Name = "Manager",
                            ServiceChargePercentage = 25m,
                            ShiftType = "Morning",
                            TotalHours = 9m
                        });
                });

            modelBuilder.Entity("Hummingbird.API.Models.TimeAttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("ClockIn")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ClockOut")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPenalty")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode", "Date")
                        .IsUnique();

                    b.ToTable("TimeAttendanceRecords");
                });

            modelBuilder.Entity("Hummingbird.API.Models.Employee", b =>
                {
                    b.HasOne("Hummingbird.API.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Hummingbird.API.Models.PayrollRecord", b =>
                {
                    b.HasOne("Hummingbird.API.Models.Employee", "Employee")
                        .WithMany("PayrollRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hummingbird.API.Models.Employee", b =>
                {
                    b.Navigation("PayrollRecords");
                });

            modelBuilder.Entity("Hummingbird.API.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
